In [1]:
import pandas as pd

geo_df = pd.read_csv("/content/spacex_launch_geo.csv")

print("Dataset shape:", geo_df.shape)
print("Columns:", geo_df.columns.tolist())
display(geo_df.head())

Dataset shape: (56, 14)
Columns: ['Flight Number', 'Date', 'Time (UTC)', 'Booster Version', 'Launch Site', 'Payload', 'Payload Mass (kg)', 'Orbit', 'Customer', 'Mission Outcome', 'Landing Outcome', 'class', 'Lat', 'Long']

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Mission Outcome,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Success,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),Success,No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356

In [2]:
for col in geo_df.columns:
    print(col, ":", geo_df[col].dtype)

Flight Number : int64
Date : object
Time (UTC) : object
Booster Version : object
Launch Site : object
Payload : object
Payload Mass (kg) : float64
Orbit : object
Customer : object
Mission Outcome : object
Landing Outcome : object
class : int64
Lat : float64
Long : float64

In [4]:
print("Available columns:")
print(geo_df.columns.tolist())

print("\nFirst 5 rows:")
display(geo_df.head())

Available columns:
['Flight Number', 'Date', 'Time (UTC)', 'Booster Version', 'Launch Site', 'Payload', 'Payload Mass (kg)', 'Orbit', 'Customer', 'Mission Outcome', 'Landing Outcome', 'class', 'Lat', 'Long']

First 5 rows:

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Mission Outcome,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Success,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),Success,No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356

In [5]:
# Clean column names
geo_df.columns = geo_df.columns.str.strip()

# Automatically find latitude and longitude columns
LAT_COL = next(
    (col for col in geo_df.columns
     if "latitude" in col.lower() or col.lower() in ["lat", "latitudes"]),
    None
)

LON_COL = next(
    (col for col in geo_df.columns
     if "longitude" in col.lower() or col.lower() in ["lon", "lng", "long"]),
    None
)

print("Latitude column:", LAT_COL)
print("Longitude column:", LON_COL)

if LAT_COL is None or LON_COL is None:
    raise ValueError(
        "Coordinate columns not detected. Check the column names printed in Step 1."
    )

# Convert coordinates to numeric
geo_df[LAT_COL] = pd.to_numeric(geo_df[LAT_COL], errors="coerce")
geo_df[LON_COL] = pd.to_numeric(geo_df[LON_COL], errors="coerce")

# Remove missing or invalid coordinates
geo_df = geo_df.dropna(subset=[LAT_COL, LON_COL])

# Keep valid geographic coordinates only
geo_df = geo_df[
    geo_df[LAT_COL].between(-90, 90) &
    geo_df[LON_COL].between(-180, 180)
].copy()

print("Valid coordinate rows:", len(geo_df))
display(geo_df.head())

Latitude column: Lat
Longitude column: Long
Valid coordinate rows: 56

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Mission Outcome,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Success,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),Success,No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),Success,No attempt,0,28.562302,-80.577356

In [6]:
!pip -q install folium

import folium

# Center the map around the launch sites
center_lat = geo_df[LAT_COL].mean()
center_lon = geo_df[LON_COL].mean()

launch_map = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=4
)

# Add a marker for every launch
for _, row in geo_df.iterrows():
    folium.Marker(
        location=[row[LAT_COL], row[LON_COL]],
        popup=(
            f"Flight Number: {row['Flight Number']}<br>"
            f"Launch Site: {row['Launch Site']}<br>"
            f"Date: {row['Date']}<br>"
            f"Landing Outcome: {row['Landing Outcome']}"
        ),
        tooltip=row["Launch Site"]
    ).add_to(launch_map)

launch_map

In [7]:
launch_map.save("spacex_launch_map_created.html")

print("Map saved successfully!")

Map saved successfully!

In [8]:
from google.colab import files

files.download("spacex_launch_map_created.html")